import MillenniumSuite.PC_NS
import MillenniumSuite.NS_YM
import MillenniumSuite.YM_Hodge
import MillenniumSuite.Hodge_BSD
import MillenniumSuite.BSD_RH
import MillenniumSuite.RH_PNP
import MillenniumSuite.PNP_PC

/-!
# Proof audit

As in `openai/NavierStokesAndEuler`, exported closed lemmas are inspected with
`#print axioms`. Open target propositions are definitions, not asserted facts.
-/

#print axioms MillenniumSuite.PCNS.sphere3_radius
#print axioms MillenniumSuite.PCNS.sphere3_norm
#print axioms MillenniumSuite.PCNS.smooth_equiv_sphere_of_poincare
#print axioms MillenniumSuite.PCNS.enstrophy_differential_bound
#print axioms MillenniumSuite.PCNS.ricci_damping_nonpositive
#print axioms MillenniumSuite.PCNS.viscous_dissipation_nonpositive
#print axioms MillenniumSuite.PCNS.physical_damping_signs
#print axioms MillenniumSuite.PCNS.continuous_profile_bkm_finite
#print axioms MillenniumSuite.PCNS.cubic_absorbed_by_ricci
#print axioms MillenniumSuite.PCNS.enstrophy_differential_bound_under_curvature_threshold

#print axioms MillenniumSuite.NSYM.curvature_swap
#print axioms MillenniumSuite.NSYM.curvature_self
#print axioms MillenniumSuite.NSYM.integrable_sq_of_memLp_two
#print axioms MillenniumSuite.NSYM.integrable_actionDensity_of_memLp_two
#print axioms MillenniumSuite.NSYM.correlation_implies_positive_mass_gap
#print axioms MillenniumSuite.NSYM.dissipative_inverse_positive
#print axioms MillenniumSuite.NSYM.kolmogorovLength_pos
#print axioms MillenniumSuite.NSYM.kolmogorovLength_inv_pos
#print axioms MillenniumSuite.NSYM.correlationHypotheses_from_kolmogorov
#print axioms MillenniumSuite.NSYM.positive_mass_gap_from_kolmogorov_control

#print axioms MillenniumSuite.YMHodge.residual_square_sum_zero
#print axioms MillenniumSuite.YMHodge.minimum_forces_hermitian_einstein
#print axioms MillenniumSuite.YMHodge.he_residual_fields_vanish
#print axioms MillenniumSuite.YMHodge.rational_linear_combination_mem
#print axioms MillenniumSuite.YMHodge.class_mem_of_eq_rational_cycle_sum
#print axioms MillenniumSuite.YMHodge.algebraic_class_of_eq

#print axioms MillenniumSuite.HodgeBSD.bounds_give_rank_equality
#print axioms MillenniumSuite.HodgeBSD.arithmetic_bounds_give_bsd
#print axioms MillenniumSuite.HodgeBSD.posDef_regulator_det_ne_zero
#print axioms MillenniumSuite.HodgeBSD.weakBSDQ_of_bounds

#print axioms MillenniumSuite.BSDRH.functional_equation_zero_symmetry
#print axioms MillenniumSuite.BSDRH.zero_gives_scattering_denominator_zero
#print axioms MillenniumSuite.BSDRH.symmetric_zero_left_of_line
#print axioms MillenniumSuite.BSDRH.actual_completed_zeta_functional_equation
#print axioms MillenniumSuite.BSDRH.actual_completed_zeta_zero_symmetry
#print axioms MillenniumSuite.BSDRH.actual_zero_gives_scattering_denominator_zero
#print axioms MillenniumSuite.BSDRH.riemann_zero_to_completed_of_re_pos
#print axioms MillenniumSuite.BSDRH.right_riemann_zero_gives_actual_scattering_denominator_zero
#print axioms MillenniumSuite.BSDRH.right_riemann_zero_reflects_left
#print axioms MillenniumSuite.BSDRH.residue_term_negative
#print axioms MillenniumSuite.BSDRH.maass_selberg_positivity_contradiction
#print axioms MillenniumSuite.BSDRH.residue_mechanism_of_pole_and_contour
#print axioms MillenniumSuite.BSDRH.no_right_zero_of_pole_and_contour
#print axioms MillenniumSuite.BSDRH.no_right_riemann_zero_of_residue_mechanism
#print axioms MillenniumSuite.BSDRH.zeta_zero_re_le_half_of_spectral_data
#print axioms MillenniumSuite.BSDRH.noOffCritical_iff_RH

#print axioms MillenniumSuite.RHPNP.literalPenalty_eq_zero_iff
#print axioms MillenniumSuite.RHPNP.clausePenalty_eq_zero_iff
#print axioms MillenniumSuite.RHPNP.formulaPenalty_eq_zero_iff
#print axioms MillenniumSuite.RHPNP.satisfiable_iff_exists_zero_penalty
#print axioms MillenniumSuite.RHPNP.zeroPenaltyEncoding
#print axioms MillenniumSuite.RHPNP.literalPenalty_zero_or_one
#print axioms MillenniumSuite.RHPNP.clausePenalty_zero_or_one
#print axioms MillenniumSuite.RHPNP.formulaPenalty_eq_unsatisfiedClauseCount
#print axioms MillenniumSuite.RHPNP.unsatisfiedClauseCount_le_length
#print axioms MillenniumSuite.RHPNP.formulaSatisfied_iff_unsatisfiedClauseCount_eq_zero
#print axioms MillenniumSuite.RHPNP.boolToSign_injective
#print axioms MillenniumSuite.RHPNP.symmetricCubeToAssignment_assignmentToSymmetricCube
#print axioms MillenniumSuite.RHPNP.assignmentToSymmetricCube_symmetricCubeToAssignment
#print axioms MillenniumSuite.RHPNP.p_subset_np
#print axioms MillenniumSuite.RHPNP.pEqualsNP_iff_np_subset_p
#print axioms MillenniumSuite.RHPNP.gueKernel_zero
#print axioms MillenniumSuite.RHPNP.gueKernel_nonneg
#print axioms MillenniumSuite.RHPNP.gueKernel_le_one
#print axioms MillenniumSuite.RHPNP.continuous_gueKernel
#print axioms MillenniumSuite.RHPNP.zero_count_below_quarter
#print axioms MillenniumSuite.RHPNP.positive_count_above_three_quarters
#print axioms MillenniumSuite.RHPNP.quarter_gap_separates_counts
#print axioms MillenniumSuite.RHPNP.satisfiable_iff_satisfyingCount_pos
#print axioms MillenniumSuite.RHPNP.not_satisfiable_iff_satisfyingCount_eq_zero
#print axioms MillenniumSuite.RHPNP.satisfiable_iff_approximation_above_three_quarters

#print axioms MillenniumSuite.PNPPC.PachnerReachable.trans
#print axioms MillenniumSuite.PNPPC.extend_sphere_certificate
#print axioms MillenniumSuite.PNPPC.reachable_iff_exists_finite_chain
#print axioms MillenniumSuite.PNPPC.verifyPachnerChain_eq_true_iff
#print axioms MillenniumSuite.PNPPC.reachable_iff_exists_accepted_certificate
#print axioms MillenniumSuite.PNPPC.sphere_recognition_inP_of_pEqualsNP
